language = "C"
header = "// Copyright 2024 Google LLC\n// SPDX-License-Identifier: MIT"
include_guard = "HBM_MINIGBM_H"
include_version = true
sys_includes = ["sys/types.h"]
cpp_compat = true
style = "tag"

[enum]
rename_variants = "QualifiedScreamingSnakeCase"
